project:
  type: website
  output-dir: docs

website:
  title: "Simon Ghyselincks"
  description: "A personal page for Simon Ghyselincks"
  page-navigation: true

  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Learning to Balance"
        href: content/projects/RLUnicycle/introduction.qmd
      - text: "CV"
        href: www/cv/CV.pdf
      - text: "About"
        href: content/about/biography.qmd

  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Home"
        href:  index.qmd 

      - section: "Projects"
        contents:
          - content/projects/projects.qmd
          - section: "Learning to Balance"
            contents:
              - content/projects/RLUnicycle/introduction.qmd
              - content/projects/RLUnicycle/rtpatch.qmd
              - content/projects/RLUnicycle/telemetry.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true