project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - index.qmd
      - section: "Learning to Balance"
        contents:
          - RLUnicycle/introduction.qmd
          - RLUnicycle/rtpatch.qmd
          - RLUnicycle/telemetry.qmd
  title: "Simon Ghyselincks"
  description: "A personal page for Simon Ghyselincks"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Learning to Balance"
        href: RLUnicycle/introduction.qmd
      - text: "CV"
        href: CV.pdf

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
