project:
  type: website
  output-dir: _site

execute:
  freeze: auto

website:
  title: "Simon Ghyselincks"
  description: "A personal page for Simon Ghyselincks"
  site-url: "https://chipnbits.github.io"
  site-path: "/"
  page-navigation: true
  open-graph: true
  twitter-card: true

  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Bio"
        href: content/about/biography.qmd
      - text: "Publications"
        href: content/publications/index.qmd
      - text: "Talks & Teaching"
        href: content/talks/index.qmd
      - text: "Projects"
        menu:
          - text: "EOSC 555"
            href: content/eosc555/index.qmd
          - text: "Learning to Balance"
            href: content/projects/RLUnicycle/introduction.qmd
      - text: "Blog"
        href: blog/index.qmd

  page-footer: 
    left: '© 2026, Simon Ghyselincks'
    right: 
      - icon: house
        href: https://chipnbits.github.io/
      - icon: github
        href: https://github.com/chipnbits

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header: google-site-verification.html
    filters: 
      - shinylive