project:
  type: website
  output-dir: docs
  render:
    - "**"                   
    - "!content/eosc555/**"  # EXCLUDE EOSC 555 from builds (frozen)
    - "!blog/**"             # EXCLUDE RL unicycle from builds (frozen

website:
  title: "Simon Ghyselincks"
  description: "A personal page for Simon Ghyselincks"
  site-url: "https://chipnbits.github.io"
  site-path: "/"
  page-navigation: true

  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: content/publications/index.qmd
      - text: "Blog" 
        href: blog/index.qmd
      # - text: "CV"
      #   href: www/cv/CV.pdf
      - text: "EOSC 555"  # New navigation item
        href: content/eosc555/index.qmd
      - text: "Learning to Balance"
        href: content/projects/RLUnicycle/introduction.qmd
      - text: "Bio"
        href: content/about/biography.qmd

  page-footer: 
    left: '© 2025, Simon Ghyselincks'
    right: 
      - icon: house
        href: https://chipnbits.github.io/
      - icon: github
        href: https://github.com/chipnbits

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header: google-site-verification.html