---
title: "Simon Ghyselincks"
format: html
css: CVstyles.css
includes:
  in-header: head.html
---
Vancouver, BC  
V6T 1Z1

- Phone: [604-789-8492](tel:16047898492)
- Email: [sghyselincks@(popular service from google).com](mailto:sghyselincks@gmail.com)
- LinkedIn: [simonghyselincks](https://www.linkedin.com/in/simonghyselincks/)
- GitHub: [chipnbits](https://github.com/chipnbits)

## Education

- **University of British Columbia**  
  _BASc in Engineering Physics, Minor in Computer Science_  
  Vancouver, British Columbia  
  Sep 2020 – May 2025 (Expected)  
  Cumulative GPA: 95%

## Research Interests

- **Computational Modeling and Simulation:** Numerical algorithms for simulating physical systems, computational optimization, applied linear algebra, applications in robotics and signal processing.
- **Machine Learning and Computer Vision:** Applied machine learning and deep learning, interpretable AI and network dissection, computer vision for robotics, 3D environmental reconstruction.

## Research Experience

- **UBC ATLAS Group**  
  _USRA Undergraduate Research Assistant_  
  Vancouver, BC, Canada  
  May 2023 – Aug 2023  
  Supervisors: Cole Helling and Alison Lister  
  - Contributed to the testing and characterization of sensor modules for the new ATLAS detector at CERN’s Large Hadron Collider.
  - Identified the source of a critical software and hardware issue.
  - Collaborated on design and implementation of safety protocols for the controls and monitoring system.

## Projects

- **[Computer Vision - Personal](https://github.com/chipnbits/LearningPytorch/tree/cuda)**  
  PyTorch Projects  
  Dec 2023 - Present  
  - Comparative analysis of image classification methods.

- **[Reinforcement Learning Reaction Wheel Unicycle - Capstone](https://docs.google.com/presentation/d/10Ljghkfzt6N9AoEjKxOUTnJAiNcLO6c3/edit?usp=drive_link&ouid=109283385050251445631&rtpof=true&sd=true)**  
  Aug 2023 - Present  
  - Team leader in physics and control modeling, telemetry, and environmental sensing.

## Skills

- **Programming Languages:** Python, C/C++, Java, MATLAB, Julia
- **Software and Tools:** Linux, ROS, Gazebo, Simulink, Git, Grafana, InfluxDB
- **Machine Learning and AI:** Deep Learning, Keras, PyTorch, OpenCV Libraries, Data Analysis and Modeling, Regression Based Models, PCA
- **Mathematics:** Applied Linear Algebra, Statistics and Probability, Complex Analysis, Signals Processing, Applied PDEs and ODEs
- **Engineering:** Robotics, Controls, Microcontrollers (STM32, Raspberry Pi, Nvidia Jetson), FPGAs, PCB Design, Machine Design, 3D Printing, CAD (SolidWorks, Onshape), Circuit Analysis
- **Languages:** English (Native), Spanish (Proficient), French (Proficient)

## Scholarships & Awards

- **2023 NSERC Undergraduate Student Research Award**
- **2021/22/23 Trek Excellence Scholarship**
- **2023 Novicov Scholarship**
- **2022 Eric P. Newell Leadership Award**

## Organizations

- Engineers and Geoscientists BC (Dec 2021 – Present)
- Canadian Association of Physicists (Jan 2023 – Present)
- Vancouver Julia Users (Nov 2023 – Present)

## Hobbies

- Trekking, Classical Guitar, Peruvian Folklore, Drift Skates, Reading Biographies, Chinese Traditional Tea

