---
title: "Simon's Personal Website"
description: "Simon Ghyselincks - PhD student at UBC Computer Science, researching AI, and computational science"
---

## Welcome
Welcome to my personal site! I'm Simon Ghyselincks, a PhD-track student at the University of British Columbia (UBC) in the Department of Computer Science. 

## Academics
I completed my BASc in Engineering Physics with a minor in Computer Science at UBC in 2025. My undergraduate two-year senior capstone project was "Learning to Balance" which explored the application of reinforcement learning to a reaction wheel robot with complex dynamics. Read more about it [here](/content/projects/RLUnicycle/introduction.qmd).

I am currently working with Professor [Eldad Haber](https://scholar.google.ca/citations?user=NZmEIS8AAAAJ&hl=en) from UBC Earth and Ocean Sciences and Professor [Evan Shelhamer](https://scholar.google.ca/citations?user=-ltRSM0AAAAJ&hl=en) from UBC Computer Science on scientific machine learning and generative AI with broad applications to geophysics and other fields. You can find my recent publications [here](/content/publications/index.qmd).



<!-- ## Looking Forward

I am interested in a Masters or PhD in the field of robotics, computational science and engineering, machine learning, or the intersection of all three!  -->

Feel free to connect with me on [LinkedIn](https://www.linkedin.com/in/simonghyselincks) or check out my [GitHub](https://github.com/chipnbits).

## My Journey

Read more about my journey and past pursuits [here](/content/about/biography.qmd).
